### ISSUE TITLE
[BUG] CSS import URL with single quote doesn't change color

### ISSUE THREAD

**Issue by fumihito-sama** [irfanshadikrishad/meow#1]
`@import url('https://fonts.googleapis.com/css2?family=Macondo&display=swap');`

![image_2023-12-20_014857357](https://github.com/irfanshadikrishad/meow/assets/40922985/b9cbf877-4eb5-436e-9733-e00bf2275ff9)

**Comment by irfanshadikrishad** [comment]
fixed #1 here 66d0ee90c20a71e63b24bde4c8322e5dec88c791
