### ISSUE TITLE
Bug: no color on super, get & set keyword

### ISSUE THREAD

**Issue by xQ6o** [irfanshadikrishad/meow#6]
![image](https://github.com/irfanshadikrishad/meow/assets/101199747/0b21bf8f-7d2e-4a56-b7e2-fe63dabc9825)
![image](https://github.com/irfanshadikrishad/meow/assets/101199747/07ce7ba5-7aec-41b7-9917-a39692047112)
![image](https://github.com/irfanshadikrishad/meow/assets/101199747/cbdf2e7e-bf1f-401a-8da5-c9c1b534e8db)

**Comment by xQ6o** [comment]
no color on node shebang
![image](https://github.com/irfanshadikrishad/meow/assets/101199747/2a04572e-9e51-492e-9392-a1ecec18d135)

**Comment by irfanshadikrishad** [comment]
fixed be1b583432c2b9d733da8d7157ac38c8524c577b
